name: "web-aplication-schema"
services: 
  db:
    image: mysql
    restart: always
    container_name: database
    ports:
      - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - db_volume:/var/lib/mysql

  web-server:
    image: php:8.1.18-apache
    container_name: web-server
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
     - 8080:80
    environment:
      - PMA_ARBITRARY=1
  
volumes:
  db_volume: {}